country_dict = {'American Samoa': 'American Samoa (USA)',
'Anguilla':'Anguilla (UK)',
'Aruba':'Aruba (Neth.)',
'Bermuda':'Bermuda (UK)',
'Bolivia':'Bolivia (Plurinational State of)',
'British Virgin Islands':'British Virgin Islands (UK)',
'Brunei':'Brunei Darussalam',
'Cayman Islands': 'Cayman Islands (UK)',
'Christmas Island':'Christmas Island (Aust.)',
'Cocos (Keeling) Islands': 'Cocos (Keeling) Islands (Aust.)',
'Congo (Brazzaville)':'Congo',
'Congo (Kinshasa)':'Democratic Republic of the Congo',
'Cook Islands': 'Cook Islands (NZ)',
'Cote d’Ivoire': "Côte d'Ivoire",
'Curacao': 'Curaçao (Neth.)',
'Faroe Islands':'Faroe Islands (Den.)',
'French Guiana':'French Guiana (Fr.)',
'French Polynesia':'French Polynesia (Fr.)',
'Gaza Strip':'Gaza',
'Gibraltar':'Gibraltar (UK)',
'Greenland':'Greenland (Den.)',
'Guadeloupe':'Guadeloupe (Fr.)',
'Guam':'Guam (USA)',
'Guernsey':'Guernsey (UK)',
'Iran': 'Iran (Islamic Republic of)',
'Isle of Man':'Isle of Man (UK)',
'Jersey': 'Jersey (UK)',
'Laos':"Lao People's Democratic Republic",
'Martinique':'Martinique (Fr.)',
'Mayotte': 'Mayotte (Fr.)',
'Micronesia':'Micronesia (Federated States of)',
'Moldova': 'Republic of Moldova',
'Montserrat':'Montserrat (UK)',
'New Caledonia':'New Caledonia (Fr.)',
'Niue': 'Niue (NZ)',
'Norfolk Island':'Norfolk Island (Aust.)',
'North Korea': "Democratic People's Republic of Korea",
'Northern Mariana Islands':'Northern Mariana Islands (USA)',
'Pitcairn Islands': 'Pitcairn (UK)',
'Puerto Rico': 'Puerto Rico (USA)',
'Reunion': 'Réunion (Fr.)',
'Russia': 'Russian Federation',
'Saint Barthelemy':'Saint Barthélemy (Fr.)',
'Sint Maarten':'Sint Maarten (Neth.)',
'South Korea':'Republic of Korea',
'Svalbard':'Svalbard Islands (Nor.)',
'Syria':'Syrian Arab Republic',
'Tanzania':'United Republic of Tanzania',
'Tokelau':'Tokelau (NZ)',
'Turks and Caicos Islands': 'Turks and Caicos Islands (UK)',
'Türkiye':'Turkey',
'United Kingdom':'United Kingdom of Great Britain and Northern Ireland',
'United States': 'United States of America',
'Venezuela': 'Venezuela (Bolivarian Republic of)',
'Vietnam': 'Viet Nam',
'Virgin Islands': 'United States Virgin Islands (USA)',
'Wallis and Futuna':'Wallis and Futuna Islands (Fr.)',
}